//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace УчётПлатежей
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class УчётПлатежейEntities : DbContext
    {
        public УчётПлатежейEntities()
            : base("name=УчётПлатежейEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<категории> категории { get; set; }
        public virtual DbSet<платежи> платежи { get; set; }
        public virtual DbSet<пользователи> пользователи { get; set; }
        public virtual DbSet<продукты> продукты { get; set; }
    }
}
