//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace УчётПлатежей
{
    using System;
    using System.Collections.Generic;
    
    public partial class платежи
    {
        public int id_платежа { get; set; }
        public Nullable<System.DateTime> дата_платежа { get; set; }
        public Nullable<int> id_продукта { get; set; }
        public Nullable<int> количество { get; set; }
        public Nullable<decimal> итоговая_стоимость { get; set; }
        public Nullable<int> id_пользователя { get; set; }
        public Nullable<decimal> сумма_со_скидкой { get; set; }
    
        public virtual пользователи пользователи { get; set; }
        public virtual продукты продукты { get; set; }
    }
}
