//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace УчётПлатежей
{
    using System;
    using System.Collections.Generic;
    
    public partial class пользователи
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public пользователи()
        {
            this.платежи = new HashSet<платежи>();
        }
    
        public int id_пользователя { get; set; }
        public string фио { get; set; }
        public string логин { get; set; }
        public string пароль { get; set; }
        public string пин_код { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<платежи> платежи { get; set; }
    }
}
