//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace УчётПлатежей
{
    using System;
    using System.Collections.Generic;
    
    public partial class продукты
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public продукты()
        {
            this.платежи = new HashSet<платежи>();
        }
    
        public int id_продукта { get; set; }
        public string наименование { get; set; }
        public Nullable<decimal> цена { get; set; }
        public Nullable<int> id_категории { get; set; }
        public string описание { get; set; }
    
        public virtual категории категории { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<платежи> платежи { get; set; }
    }
}
